spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://host:port/postgres
      username: postgres
      password: password
    jpa:
      properties.hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate:
        ddl-auto: validate